### ISSUE TITLE
App/file extension?

### ISSUE THREAD

**Issue by AlleyCatSunflower** [cochrane/GLLara#118]
Not an issue in-program, per se, but I don't know how else to resolve this. I have a Mac with OS 10.13.4 and downloaded the latest version, but trying to open it causes this error message:
![screen shot 2018-06-05 at 12 51 00 am](https://user-images.githubusercontent.com/39944126/40962506-8f14bc70-685a-11e8-92be-5e9eb15c6e14.png)
Maybe I'm just technologically inept, or this is a different/personal issue, but I think I need to know the app extension before I can use it, since there is no assigned program to open the 'file' and I don't know how to tell my computer that GLLara IS a program. Any suggestions?

**Comment by cochrane** [comment]
I don’t think this has anything to do with extensions at all. Could you try downloading an older version to see whether the error occurs there as well?

(The correct extension would be .app, by the way)

**Comment by AlleyCatSunflower** [comment]
Got the exact same process and error message with 2.7. But don't worry too much about it; it's probably an issue on my end. Thanks anyway!
