### ISSUE TITLE
Support for optional parts

### ISSUE THREAD

**Issue by cochrane** [cochrane/GLLara#16]
Optional parts are not supported directly. They are sort of supported (on a mesh level), but I think XNALara also has multiple-mesh optional parts. That should be added.

**Comment by jhfong** [comment]
I'd like to see GLLara honor XNALara's convention where a mesh name that begins with "-" is disabled by default.

**Comment by cochrane** [comment]
Actually come to think of it, this doesn't need any scene format changes. Just a nicer UI to bulk enable/disable meshes.
